
const COMMON = {
    UPDATED_SUCCESSFULLY: 'updated successfully!',
    CREATED_SUCCESSFULLY: 'created successfully!',
    DELETED: 'deleted!',
    IS_REQUIRED: 'is required',
    NOT_FOUND: 'not found',
}

const MESSAGE = {
    SERVER_ERROR: 'Server error',
    LOGIN_SUCCESSFULLY: 'Login successfully',
    EMAIL_ALREADY_EXIST: 'Email already exist',
    DOMAIN_ALREADY_EXIST: 'Domain already exist',
    EMAIL_PASSWORD_NOT_CORRECT: 'Email password not correct',
    
    ROLE_CREATED_SUCCESSFULLY: `Role ${COMMON.CREATED_SUCCESSFULLY}`,
    MASTER_CREATED_SUCCESSFULLY: `Master ${COMMON.CREATED_SUCCESSFULLY}`,
    DATABASE_CREATED_SUCCESSFULLY: `Database ${COMMON.CREATED_SUCCESSFULLY}`,
    
    USER_UPDATED_SUCCESSFULLY: `User ${COMMON.UPDATED_SUCCESSFULLY}`,
    ROLE_UPDATED_SUCCESSFULLY: `Role ${COMMON.UPDATED_SUCCESSFULLY}`,
    MASTER_UPDATED_SUCCESSFULLY: `Master ${COMMON.UPDATED_SUCCESSFULLY}`,
    MASTER_DELETED_SUCCESSFULLY: `Master ${COMMON.UPDATED_SUCCESSFULLY}`,
    MASTER: {
        DELETED: `Master ${COMMON.DELETED}`
    }

}

module.exports = {
    MESSAGE
};